There is a bug in the code
The bug is not in the official marlin 2.1.x bugfixes folder but I can find him here. If you try to compile marlin with your marlin-folder you get an error:

Marlin\src\lcd/e3v2/proui/dwin.h:123:21: error: 'LEVELING_BED_TEMP' was not declared in this scope
  123 |   int16_t BedLevT = LEVELING_BED_TEMP;
      |    

This error occurs because the variable "LEVELING_BED_TEMP" doesn't exist if disable Preheat before levelling ==> //#define PREHEAT_BEFORE_LEVELING

You should implement a way to only use the "LEVELING_BED_TEMP"-variable when "PREHEAT_BEFORE_LEVELING" is enabled.